name: API Tests

on:
  push:
    branches:
      - '**'  # Triggers on all branches

  pull_request:
    branches:
      - main  # Also runs on PRs targeting the 'main' branch

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specific branch that triggered the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # Ensure the correct branch is checked out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: Run API Tests
        run: |
          cd backend
          pytest --cov=app/controllers --cov-report=term-missing
